_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  RPN:
    PRE_NMS_TOPK_TRAIN: 1500  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1

