_BASE_: "Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  WEIGHTS: "catalog://ImageNetPretrained/MSRA/R-50"
  MASK_ON: False

  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseAMAHead"
    INTER_WEIGHTS: 0.5
    CONV_HEAD_DIM: 256

  ROI_MASK_HEAD:
    RCNN_HEAD_ON: False
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1

